@startuml
title UserService State Diagram

[*] --> GeneratingVerificationLink : generateVerificationLink(user: User)
GeneratingVerificationLink --> VerifyingUser : verifyUserByToken(token: String)
VerifyingUser --> [*]

@enduml
